feat: Add pre-commit hook with Husky

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,18 +1,17 @@
-# Using echo to create the file and add content
-echo '#!/bin/sh' > pre-commit
-echo '. "$(dirname "$0")/_/husky.sh"' >> pre-commit # Keep this line, it's added by Husky init
-echo '' >> pre-commit # Add an empty line for readability
-echo 'echo "Running tests before commit..."' >> pre-commit
-echo '' >> pre-commit
-echo 'pnpm test || {' >> pre-commit # IMPORTANT: Use 'pnpm test' as per your query
-echo '  echo ""' >> pre-commit
-echo '  echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"' >> pre-commit
-echo '  echo "!!! TESTS FAILED! COMMIT ABORTED.       !!!"' >> pre-commit
-echo '  echo "!!! Please fix the tests and try again. !!!"' >> pre-commit
-echo '  echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"' >> pre-commit
-echo '  echo ""' >> pre-commit
-echo '  exit 1' >> pre-commit
-echo '}' >> pre-commit
-echo '' >> pre-commit
-echo 'echo "Tests passed! Proceeding with commit."' >> pre-commit
-echo 'exit 0' >> pre-commit
+#!/bin/sh
+. "$(dirname "$0")/_/husky.sh"
+
+echo "Running tests before commit..."
+
+pnpm test || {
+  echo ""
+  echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
+  echo "!!! TESTS FAILED! COMMIT ABORTED.       !!!"
+  echo "!!! Please fix the tests and try again. !!!"
+  echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
+  echo ""
+  exit 1
+}
+
+echo "Tests passed! Proceeding with commit."
+exit 0
